Sf2MCQ\CoreBundle\Entity\Interview:
  type: entity
  table: interview
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 255
    duration:
      type: integer
  oneToMany:
    questions:
      targetEntity: Question
      mappedBy: interview
  manyToOne:
    level:
      targetEntity: Level
      inversedBy: interviews
    subject:
      targetEntity: Subject
      inversedBy: interviews
      
