Sf2MCQ\CoreBundle\Entity\Proposition:
  type: entity
  table: proposition
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  manyToOne:
    test:
      targetEntity: Test
      inversedBy: propositions
    question:
      targetEntity: Question
      inversedBy: questions
  manyToMany:
    answers:
      targetEntity: Answer
      joinTable: 
        name: proposition_answers
        joinColumns:
          proposition_id:
            referencedColumnName: id
        inverseJoinColumns:
          answer_id:
            referencedColumnName: id
      
      

