Sf2MCQ\CoreBundle\Entity\Proposition:
  type: entity
  table: proposition
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  oneToOne:
    question:
      targetEntity: Question
  manyToOne:
    test:
      targetEntity: Test
      inversedBy: propositions
  manyToMany:
    answers:
      targetEntity: Answer
      joinTable: 
        name: proposition_answers
        joinColumns:
          proposition_id:
            referencedColumnName: id
        inverseJoinColumns:
          answer_id:
            referencedColumnName: id
            unique: true
      
      

