Sf2MCQ\CoreBundle\Entity\Question:
  type: entity
  table: question
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    content:
      type: text
    code:
      type: text
      nullable: true
    points:
      type: integer
  oneToMany:
    answers:
      targetEntity: Answer
      mappedBy: question
      cascade:
        - persist
        - delete
  manyToOne:
    interview:
      targetEntity: Interview
      inversedBy: questions
    language:
      targetEntity: Language
      inversedBy: questions
      
