Sf2MCQ\CoreBundle\Entity\Question:
  type: entity
  table: question
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    content:
      type: text
      length: 255
    points:
      type: integer
  oneToMany:
    answers:
      targetEntity: Answer
      mappedBy: question
  manyToOne:
    interview:
      targetEntity: Interview
      inversedBy: questions
      
