Sf2MCQ\CoreBundle\Entity\Subject:
  type: entity
  table: subject
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 255
    description:
      type: text
  oneToMany:
    interviews:
      targetEntity: Interview
      mappedBy: subject
  manyToOne:
    category:
      targetEntity: Category
      inversedBy: subjects
    
