homepage:
  pattern: /
  defaults: { _controller: Sf2MCQCoreBundle:Home:index }

subject:
  pattern: /subject/{id}/{slug}
  defaults: { _controller: Sf2MCQCoreBundle:Subject:index }

start_interview:
  pattern: /interview/{id}/
  defaults: { _controller: Sf2MCQCoreBundle:Interview:index }
