homepage:
  pattern: /
  defaults: { _controller: Sf2MCQCoreBundle:Home:index }

subject:
  pattern: /subject/{id}/{slug}
  defaults: { _controller: Sf2MCQCoreBundle:Subject:index }

start_interview:
  pattern: /interview/{id}
  defaults: { _controller: Sf2MCQCoreBundle:Interview:index }
  
test:
  pattern: /test/{index}
  defaults: { _controller: Sf2MCQCoreBundle:Test:show }
  
submit_answer:
  pattern: /test-answer
  defaults: { _controller: Sf2MCQCoreBundle:Test:answer }

test_finished:
  pattern: /test_finished
  defaults: { _controller: Sf2MCQCoreBundle:Test:finished }
