Sf2MCQ\CoreBundle\Entity\Candidate:
  properties:
    firstname:
      - NotBlank: ~
    lastname:
      - NotBlank: ~
Sf2MCQ\CoreBundle\Entity\Proposition:
    constraints:
        - Callback:
            methods:   [hasAnswers]

      
