Sf2MCQ\Bundle\Entity\Answer:
  type: entity
  table: answer
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    content:
      type: text
    valid:
      type: boolean
  oneToMany:
    question:
      targetEntity: Question
      inversedBy: answers
      
