Sf2MCQ\Bundle\Entity\Candidate:
  type: entity
  table: candidate
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    firstname:
      type: string
    lastname:
      type: string
  oneToMany:
    tests:
      targetEntity: Test
      mappedBy: candidate
      
