Sf2MCQ\Bundle\Entity\Test:
  type: entity
  table: test
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    start:
      type: datetime
    end:
      type: datetime
  manyToOne:
    candidate:
      targetEntity: Candidate
      inversedBy: tests
   propositions:
     targetEntity: proposition
     mappedBy: test
    
