Sf2MCQ\Bundle\Entity\Test:
  type: entity
  table: test
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    start:
      type: datetime
    end:
      type: datetime
  oneToMany:
    propositions:
      targetEntity: proposition
      mappedBy: test
  manyToOne:
    candidate:
      targetEntity: Candidate
      inversedBy: tests
    
